package com.telegramyou.app.ui.theme

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class PaletteTest {

    private fun hex(argb: Int) = "%08X".format(argb)

    /**
     * The teal fallback in Theme.kt was generated by hand from the same seed
     * with the same settings; built here at run time it has to come out the
     * same, or the accent picker's teal would not be the app's teal.
     */
    @Test
    fun `teal comes out as the hand-made fallback, light and dark`() {
        val light = schemeFromSeed(Accents.TEAL, dark = false)
        assertEquals("FF1D6B50", hex(light.primary))
        assertEquals("FFA7F2D0", hex(light.primaryContainer))
        assertEquals("FF4C6358", hex(light.secondary))
        assertEquals("FF3E6374", hex(light.tertiary))
        assertEquals("FFF5FBF5", hex(light.surface))
        assertEquals("FFEAEFEA", hex(light.surfaceContainer))
        assertEquals("FFFFFFFF", hex(light.surfaceContainerLowest))

        val dark = schemeFromSeed(Accents.TEAL, dark = true)
        assertEquals("FF8CD5B4", hex(dark.primary))
        assertEquals("FF00513A", hex(dark.primaryContainer))
        assertEquals("FF0F1512", hex(dark.surface))
        assertEquals("FF1B211E", hex(dark.surfaceContainer))
        assertEquals("FF0A0F0D", hex(dark.surfaceContainerLowest))
    }

    @Test
    fun `every accent makes a scheme of its own`() {
        val primaries = Accents.all.map { (_, seed) -> schemeFromSeed(seed, dark = false).primary }
        assertEquals("each accent should give a different primary", primaries.size, primaries.toSet().size)
        assertEquals("Blue", Accents.nameOf(0xFF4285F4.toInt()))
        assertNull(Accents.nameOf(0xFF123456.toInt()))
    }

    @Test
    fun `pure black takes the page to black and keeps the cards`() {
        val dark = schemeFromSeed(Accents.TEAL, dark = true)
        val black = dark.pureBlack()
        assertEquals("FF000000", hex(black.surface))
        assertEquals("FF000000", hex(black.background))
        assertEquals(dark.surfaceContainerHigh, black.surfaceContainerHigh)
        assertEquals(dark.primary, black.primary)
    }

    @Test
    fun `a picture's colour is the one it is mostly made of`() {
        // Mostly a clear red, with some white and grey.
        val pixels = IntArray(900) { 0xFFD32F2F.toInt() } + IntArray(80) { 0xFFFFFFFF.toInt() } +
            IntArray(20) { 0xFF808080.toInt() }
        val seed = seedFromPixels(pixels)
        assertNotNull(seed)
        seed!!
        val red = (seed shr 16) and 0xFF
        val green = (seed shr 8) and 0xFF
        assertTrue("expected a red seed, got ${hex(seed)}", red > 150 && green < 100)
    }

    @Test
    fun `a grey picture gives nothing to take a colour from`() {
        assertNull(seedFromPixels(IntArray(500) { 0xFF7F7F7F.toInt() }))
        assertNull(seedFromPixels(IntArray(0)))
    }
}
